### ISSUE TITLE
Onde está o arquivo requirements.txt?

### ISSUE THREAD

**Issue by danilosoarescardoso** [caioalves19/scrapy-soccer-games#1]
Fala Caio, tudo bem?

Estava vendo esse projeto e queria testá-lo, mas não encontrei o arquivo requirements.txt. Poderia subi-lo, por favor? Valeu!

**Comment by caioalves19** [comment]
Danilo, perdão pela demora. Sou iniciante e ainda não entendo perfeitamente o GitHub, acabei nem entrando aqui no último mês.

Se ainda precisar, acabei de subir lá.. acho q é pra dar certo. Acho que instalei só o Scrapy e Selenium.. o resto é dependência deles.

Abraço.
